// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akxukhkkddfqodqmdtwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFreHVraGtrZGRmcW9kcW1kdHd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTg4NzQsImV4cCI6MjA3Mzg3NDg3NH0.wWyRyAIU7XeffjIw8WHyVNeRhZl9sJF56QJFKcuSU3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});